locale: en
check-for-updates: true
swim:
  stand-up-when-damaged: true
  enabled: true
lay:
  stand-up-when-damaged: true
  headrotation: true
  player-invulnerable: false
  swing-animation: true
  prevent-use-when-invisible: false
sit:
  stand-up-when-damaged: true
