stand-up-message: §bYou've stood up
in-air: §cYou can't do this in air
collidable: false
swim-animation:
  enabled: true
  message: §bYou're swimming
  break-back: §cYou suddenly stood up, because someone tried to break your back!
lay-animation:
  message: §bYou've laid down
sit-animation:
  message: §bYou've sat down
  sit-without-command: true
