name: PosePlugin
main: ru.armagidon.sit.SitPlugin
api-version: 1.14
version: 1.4.1
description: Sit Plugin
softdepend:
  - BetterChair
commands:
  sit:
    usage: /sit
  lay:
    usage: /lay
  swim:
    usage: /swim